var listaJudete = [
{value:"Alba"},
{value:"Arad"},
{value:"Argeș"},
{value:"Bacău"},
{value:"Bihor"},
{value:"Bistrița-Năsăud"},
{value:"Botoșani"},
{value:"Brașov"},
{value:"Brăila"},
{value:"București"},
{value:"Buzău"},
{value:"Caraș-Severin"},
{value:"Călărași"},
{value:"Cluj"},
{value:"Constanța"},
{value:"Covasna"},
{value:"Dâmbovița"},
{value:"Dolj"},
{value:"Galați"},
{value:"Giurgiu"},
{value:"Gorj"},
{value:"Harghita"},
{value:"Hunedoara"},
{value:"Ialomița"},
{value:"Iași"},
{value:"Ilfov"},
{value:"Maramureș"},
{value:"Mehedinți"},
{value:"Mureș"},
{value:"Neamț"},
{value:"Olt"},
{value:"Prahova"},
{value:"Satu Mare"},
{value:"Sălaj"},
{value:"Sibiu"},
{value:"Suceava"},
{value:"Teleorman"},
{value:"Timiș"},
{value:"Tulcea"},
{value:"Vaslui"},
{value:"Vâlcea"},
{value:"Vrancea"}
];

var listaOrase = [
{value:"București",text:"București"},
{value:"Cluj",text:"Cluj-Napoca"},
{value:"Timiș",text:"Timișoara"},
{value:"Iași",text:"Iași"},
{value:"Constanța",text:"Constanța"},
{value:"Dolj",text:"Craiova"},
{value:"Brașov",text:"Brașov"},
{value:"Galați",text:"Galați"},
{value:"Prahova",text:"Ploiești"},
{value:"Bihor",text:"Oradea"},
{value:"Brăila",text:"Brăila"},
{value:"Arad",text:"Arad"},
{value:"Argeș",text:"Pitești"},
{value:"Sibiu",text:"Sibiu"},
{value:"Bacău",text:"Bacău"},
{value:"Mureș",text:"Târgu Mureș"},
{value:"Maramureș",text:"Baia Mare"},
{value:"Buzău",text:"Buzău"},
{value:"Botoșani",text:"Botoșani"},
{value:"Satu Mare",text:"Satu Mare"},
{value:"Vâlcea",text:"Râmnicu Vâlcea"},
{value:"Mehedinți",text:"Drobeta-Turnu Severin"},
{value:"Suceava",text:"Suceava"},
{value:"Neamț",text:"Piatra Neamț"},
{value:"Gorj",text:"Târgu Jiu"},
{value:"Dâmbovița",text:"Târgoviște"},
{value:"Vrancea",text:"Focșani"},
{value:"Bistrița-Năsăud",text:"Bistrița"},
{value:"Caraș-Severin",text:"Reșița"},
{value:"Tulcea",text:"Tulcea"},
{value:"Olt",text:"Slatina"},
{value:"Călărași",text:"Călărași"},
{value:"Alba",text:"Alba Iulia"},
{value:"Giurgiu",text:"Giurgiu"},
{value:"Hunedoara",text:"Deva"},
{value:"Hunedoara",text:"Hunedoara"},
{value:"Sălaj",text:"Zalău"},
{value:"Covasna",text:"Sfântu Gheorghe"},
{value:"Vaslui",text:"Bârlad"},
{value:"Vaslui",text:"Vaslui"},
{value:"Neamț",text:"Roman"},
{value:"Ialomița",text:"Slobozia"},
{value:"Cluj",text:"Turda"},
{value:"Sibiu",text:"Mediaș"},
{value:"Teleorman",text:"Alexandria"},
{value:"Ilfov",text:"Voluntari"},
{value:"Timiș",text:"Lugoj"},
{value:"Constanța",text:"Medgidia"},
{value:"Bacău",text:"Onești"},
{value:"Harghita",text:"Miercurea Ciuc"},
{value:"Maramureș",text:"Sighetu Marmației"},
{value:"Hunedoara",text:"Petroșani"},
{value:"Constanța",text:"Mangalia"},
{value:"Galați",text:"Tecuci"},
{value:"Buzău",text:"Râmnicu Sărat"},
{value:"Iași",text:"Pașcani"},
{value:"Cluj",text:"Dej"},
{value:"Mureș",text:"Reghin"},
{value:"Constanța",text:"Năvodari"},
{value:"Harghita",text:"Odorheiu Secuiesc"},
{value:"Prahova",text:"Câmpina"},
{value:"Argeș",text:"Mioveni"},
{value:"Argeș",text:"Câmpulung"},
{value:"Olt",text:"Caracal"},
{value:"Brașov",text:"Săcele"},
{value:"Brașov",text:"Făgăraș"},
{value:"Ialomița",text:"Fetești"},
{value:"Mureș",text:"Sighișoara"},
{value:"Maramureș",text:"Borșa"},
{value:"Teleorman",text:"Roșiorii de Vede"},
{value:"Argeș",text:"Curtea de Argeș"},
{value:"Alba",text:"Sebeș"},
{value:"Vaslui",text:"Huși"},
{value:"Suceava",text:"Fălticeni"},
{value:"Ilfov",text:"Pantelimon"},
{value:"Călărași",text:"Oltenița"},
{value:"Teleorman",text:"Turnu Măgurele"},
{value:"Caraș-Severin",text:"Caransebeș"},
{value:"Botoșani",text:"Dorohoi"},
{value:"Hunedoara",text:"Vulcan"},
{value:"Suceava",text:"Rădăuți"},
{value:"Brașov",text:"Zărnești"},
{value:"Hunedoara",text:"Lupeni"},
{value:"Alba",text:"Aiud"},
{value:"Hunedoara",text:"Petrila"},
{value:"Ilfov",text:"Buftea"},
{value:"Bacău",text:"Moinești"},
{value:"Mureș",text:"Târnăveni"},
{value:"Cluj",text:"Câmpia Turzii"},
{value:"Ilfov",text:"Popești-Leordeni"},
{value:"Cluj",text:"Gherla"},
{value:"Satu Mare",text:"Carei"},
{value:"Alba",text:"Cugir"},
{value:"Alba",text:"Blaj"},
{value:"Brașov",text:"Codlea"},
{value:"Bacău",text:"Comănești"},
{value:"Neamț",text:"Târgu Neamț"},
{value:"Gorj",text:"Motru"},
{value:"Covasna",text:"Târgu Secuiesc"},
{value:"Dâmbovița",text:"Moreni"},
{value:"Harghita",text:"Gheorgheni"},
{value:"Prahova",text:"Băicoi"},
{value:"Hunedoara",text:"Orăștie"},
{value:"Bihor",text:"Salonta"},
{value:"Olt",text:"Balș"},
{value:"Vâlcea",text:"Drăgășani"},
{value:"Dolj",text:"Băilești"},
{value:"Dolj",text:"Calafat"},
{value:"Dolj",text:"Filiași"},
{value:"Constanța",text:"Cernavodă"},
{value:"Suceava",text:"Câmpulung Moldovenesc"},
{value:"Prahova",text:"Breaza"},
{value:"Bihor",text:"Marghita"},
{value:"Maramureș",text:"Baia Sprie"},
{value:"Mureș",text:"Luduș"},
{value:"Olt",text:"Corabia"},
{value:"Vrancea",text:"Adjud"},
{value:"Maramureș",text:"Vișeu de Sus"},
{value:"Ilfov",text:"Bragadiru"},
{value:"Caraș-Severin",text:"Bocșa"},
{value:"Brașov",text:"Râșnov"},
{value:"Ialomița",text:"Urziceni"},
{value:"Hunedoara",text:"Brad"},
{value:"Argeș",text:"Ștefănești"},
{value:"Dâmbovița",text:"Pucioasa"},
{value:"Suceava",text:"Vatra Dornei"},
{value:"Sibiu",text:"Cisnădie"},
{value:"Prahova",text:"Mizil"},
{value:"Harghita",text:"Toplița"},
{value:"Ilfov",text:"Chitila"},
{value:"Sălaj",text:"Șimleu Silvaniei"},
{value:"Bacău",text:"Buhuși"},
{value:"Suceava",text:"Vicovu de Sus"},
{value:"Teleorman",text:"Zimnicea"},
{value:"Dâmbovița",text:"Găești"},
{value:"Suceava",text:"Gura Humorului"},
{value:"Ilfov",text:"Otopeni"},
{value:"Alba",text:"Ocna Mureș"},
{value:"Constanța",text:"Ovidiu"},
{value:"Sibiu",text:"Avrig"},
{value:"Hunedoara",text:"Simeria"},
{value:"Arad",text:"Pecica"},
{value:"Dolj",text:"Dăbuleni"},
{value:"Giurgiu",text:"Bolintin-Vale"},
{value:"Gorj",text:"Rovinari"},
{value:"Prahova",text:"Comarnic"},
{value:"Prahova",text:"Vălenii de Munte"},
{value:"Timiș",text:"Sânnicolau Mare"},
{value:"Bacău",text:"Dărmănești"},
{value:"Caraș-Severin",text:"Moldova Nouă"},
{value:"Maramureș",text:"Târgu Lăpuș"},
{value:"Bihor",text:"Săcueni"},
{value:"Teleorman",text:"Videle"},
{value:"Olt",text:"Scornicești"},
{value:"Prahova",text:"Boldești-Scăeni"},
{value:"Arad",text:"Sântana"},
{value:"Bacău",text:"Târgu Ocna"},
{value:"Ilfov",text:"Măgurele"},
{value:"Hunedoara",text:"Călan"},
{value:"Bistrița-Năsăud",text:"Beclean"},
{value:"Ialomița",text:"Țăndărei"},
{value:"Mureș",text:"Sovata"},
{value:"Caraș-Severin",text:"Oravița"},
{value:"Sălaj",text:"Jibou"},
{value:"Prahova",text:"Urlați"},
{value:"Argeș",text:"Costești"},
{value:"Iași",text:"Hârlău"},
{value:"Bihor",text:"Beiuș"},
{value:"Brăila",text:"Ianca"},
{value:"Timiș",text:"Jimbolia"},
{value:"Argeș",text:"Topoloveni"},
{value:"Olt",text:"Drăgănești-Olt"},
{value:"Prahova",text:"Sinaia"},
{value:"Buzău",text:"Nehoiu"},
{value:"Covasna",text:"Covasna"},
{value:"Satu Mare",text:"Negrești-Oaș"},
{value:"Mehedinți",text:"Strehaia"},
{value:"Suceava",text:"Dolhasca"},
{value:"Mehedinți",text:"Orșova"},
{value:"Bihor",text:"Valea lui Mihai"},
{value:"Arad",text:"Lipova"},
{value:"Constanța",text:"Murfatlar"},
{value:"Bihor",text:"Aleșd"},
{value:"Botoșani",text:"Darabani"},
{value:"Harghita",text:"Cristuru Secuiesc"},
{value:"Botoșani",text:"Flămânzi"},
{value:"Vrancea",text:"Mărășești"},
{value:"Bistrița-Năsăud",text:"Sângeorz-Băi"},
{value:"Suceava",text:"Liteni"},
{value:"Iași",text:"Târgu Frumos"},
{value:"Dâmbovița",text:"Titu"},
{value:"Hunedoara",text:"Hațeg"},
{value:"Caraș-Severin",text:"Oțelu Roșu"},
{value:"Arad",text:"Ineu"},
{value:"Bistrița-Năsăud",text:"Năsăud"},
{value:"Cluj",text:"Huedin"},
{value:"Vrancea",text:"Odobești"},
{value:"Constanța",text:"Hârșova"},
{value:"Gorj",text:"Bumbești-Jiu"},
{value:"Maramureș",text:"Seini"},
{value:"Suceava",text:"Salcea"},
{value:"Iași",text:"Podu Iloaiei"},
{value:"Constanța",text:"Eforie"},
{value:"Hunedoara",text:"Uricani"},
{value:"Covasna",text:"Baraolt"},
{value:"Prahova",text:"Bușteni"},
{value:"Satu Mare",text:"Tășnad"},
{value:"Mureș",text:"Iernut"},
{value:"Sibiu",text:"Agnita"},
{value:"Neamț",text:"Roznov"},
{value:"Tulcea",text:"Babadag"},
{value:"Vâlcea",text:"Băbeni"},
{value:"Gorj",text:"Târgu Cărbunești"},
{value:"Vaslui",text:"Negrești"},
{value:"Timiș",text:"Recaș"},
{value:"Suceava",text:"Siret"},
{value:"Tulcea",text:"Măcin"},
{value:"Arad",text:"Chișineu-Criș"},
{value:"Prahova",text:"Plopeni"},
{value:"Giurgiu",text:"Mihăilești"},
{value:"Maramureș",text:"Șomcuta Mare"},
{value:"Dâmbovița",text:"Fieni"},
{value:"Covasna",text:"Întorsura Buzăului"},
{value:"Vâlcea",text:"Călimănești"},
{value:"Vrancea",text:"Panciu"},
{value:"Arad",text:"Nădlac"},
{value:"Alba",text:"Zlatna"},
{value:"Buzău",text:"Pătârlagele"},
{value:"Sălaj",text:"Cehu Silvaniei"},
{value:"Ialomița",text:"Amara"},
{value:"Maramureș",text:"Ulmeni"},
{value:"Brașov",text:"Victoria"},
{value:"Călărași",text:"Budești"},
{value:"Caraș-Severin",text:"Anina"},
{value:"Sibiu",text:"Dumbrăveni"},
{value:"Alba",text:"Câmpeni"},
{value:"Buzău",text:"Pogoanele"},
{value:"Maramureș",text:"Tăuții-Măgherăuș"},
{value:"Gorj",text:"Tismana"},
{value:"Arad",text:"Curtici"},
{value:"Constanța",text:"Techirghiol"},
{value:"Mureș",text:"Sărmașu"},
{value:"Harghita",text:"Vlăhița"},
{value:"Suceava",text:"Cajvana"},
{value:"Botoșani",text:"Săveni"},
{value:"Dolj",text:"Segarcea"},
{value:"Arad",text:"Pâncota"},
{value:"Satu Mare",text:"Livada"},
{value:"Dâmbovița",text:"Răcari"},
{value:"Mureș",text:"Ungheni"},
{value:"Timiș",text:"Făget"},
{value:"Sibiu",text:"Tălmaciu"},
{value:"Timiș",text:"Buziaș"},
{value:"Călărași",text:"Fundulea"},
{value:"Vaslui",text:"Murgeni"},
{value:"Alba",text:"Teiuș"},
{value:"Brăila",text:"Însurăței"},
{value:"Neamț",text:"Bicaz"},
{value:"Galați",text:"Târgu Bujor"},
{value:"Bihor",text:"Ștei"},
{value:"Călărași",text:"Lehliu Gară"},
{value:"Vâlcea",text:"Horezu"},
{value:"Timiș",text:"Deta"},
{value:"Prahova",text:"Slănic"},
{value:"Olt",text:"Piatra-Olt"},
{value:"Satu Mare",text:"Ardud"},
{value:"Harghita",text:"Bălan"},
{value:"Arad",text:"Sebiș"},
{value:"Suceava",text:"Frasin"},
{value:"Vâlcea",text:"Brezoi"},
{value:"Olt",text:"Potcoava"},
{value:"Timiș",text:"Gătaia"},
{value:"Suceava",text:"Broșteni"},
{value:"Gorj",text:"Novaci"},
{value:"Mureș",text:"Miercurea Nirajului"},
{value:"Mehedinți",text:"Baia de Aramă"},
{value:"Sibiu",text:"Copșa Mică"},
{value:"Mehedinți",text:"Vânju Mare"},
{value:"Botoșani",text:"Ștefănești"},
{value:"Mureș",text:"Sângeorgiu de Pădure"},
{value:"Hunedoara",text:"Geoagiu"},
{value:"Sibiu",text:"Săliște"},
{value:"Timiș",text:"Ciacova"},
{value:"Brașov",text:"Rupea"},
{value:"Suceava",text:"Milișăuți"},
{value:"Tulcea",text:"Isaccea"},
{value:"Alba",text:"Abrud"},
{value:"Constanța",text:"Negru Vodă"},
{value:"Ialomița",text:"Fierbinți-Târg"},
{value:"Maramureș",text:"Cavnic"},
{value:"Maramureș",text:"Săliștea de Sus"},
{value:"Caraș-Severin",text:"Băile Herculane"},
{value:"Vâlcea",text:"Bălcești"},
{value:"Vâlcea",text:"Berbești"},
{value:"Brașov",text:"Ghimbav"},
{value:"Brașov",text:"Predeal"},
{value:"Gorj",text:"Țicleni"},
{value:"Prahova",text:"Azuga"},
{value:"Hunedoara",text:"Aninoasa"},
{value:"Botoșani",text:"Bucecea"},
{value:"Vâlcea",text:"Băile Olănești"},
{value:"Bacău",text:"Slănic Moldova"},
{value:"Sibiu",text:"Miercurea Sibiului"},
{value:"Tulcea",text:"Sulina"},
{value:"Alba",text:"Baia de Arieș"},
{value:"Brăila",text:"Făurei"},
{value:"Sibiu",text:"Ocna Sibiului"},
{value:"Dolj",text:"Bechet"},
{value:"Ialomița",text:"Căzănești"},
{value:"Maramureș",text:"Dragomirești"},
{value:"Vâlcea",text:"Ocnele Mari"},
{value:"Galați",text:"Berești"},
{value:"Harghita",text:"Borsec"},
{value:"Vâlcea",text:"Băile Govora"},
{value:"Bihor",text:"Vașcău"},
{value:"Bihor",text:"Nucet"},
{value:"Suceava",text:"Solca"},
{value:"Harghita",text:"Băile Tușnad"}
];

//Obiecte folosite in cadrul functiilor de selectie
var selectOras = new Object();
let selectJudet = new Object();

//Adaugare EventListener la incarcarea paginii pentru selectarea judetului
window.addEventListener("load", selJudet, false);

//Adaugare EventListener la incarcarea paginii verificarea valorii judetului
window.addEventListener("load", start, false);

//Adaugare EventListener la fiecare selectie de judet
function start(){
document.getElementById('selectieJudet').addEventListener('change', selOras, false);
}

//Functie de stergere a optiunilor apelata dupa fiecare selectie de judet
function removeOptions(selectbox) {
    for(let i = selectbox.options.length - 1 ; i >= 0 ; i--)
        selectbox.remove(i);
}

//Functie de selectare judet
function selJudet() {
selectJudet = document.getElementById('selectieJudet');
var i = 0, il=listaJudete.length;

for (; i < il; i++) {
    option = document.createElement('option');
    temp = listaJudete[i].value;
    option.setAttribute('value',temp);
    option.appendChild(document.createTextNode(temp));
    selectJudet.appendChild(option);
    }
}

//Functie de selectare oras
function selOras() {
  selectOras = document.getElementById('selectieOras');  
  removeOptions(selectOras);

  var il=listaOrase.length;
  
  for (let i=0; i < il; i++) {
    if(document.getElementById('selectieJudet').value == listaOrase[i].value) {
      option = document.createElement('option');
      temp = listaOrase[i].text;
      option.setAttribute('value',temp);
      option.appendChild(document.createTextNode(temp));
      selectOras.appendChild(option);  
      }
    }
  } 